name: provision_resources.yml
on:
  workflow_dispatch:

  push:
    branches:
      - '**'

permissions:
  id-token: write
  contents: write
  packages: read
  pull-requests: read

jobs:

  provision-resources:
    name: "Provision resources"
    runs-on: ubuntu-latest
    # TODO make the determination of the environment dynamic based on branch vs tag
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: aalloul/genesis-action/authenticate-with-gcp@v0.13.0-feat-create-bigquery-tables.1
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_NAME }}
          gcp_project: ${{ vars.PROJECT_ID }}

      - uses: aalloul/genesis-action/genesis-infra-api@v0.13.0-feat-create-bigquery-tables.1
        with:
          action: provision-resources
          config_yml_file: data_product_definition.yml
          genesis_version: v0.12.0-feat-create-bigquery-tables.1
          debug: true
          run_terraform_apply: false
          env_vars: ${{ toJSON(vars) }}
          secrets: ${{ toJSON(secrets) }}
