name: provision_resources.yml
on:
  workflow_dispatch:

  push:
    branches:
      - '**'

permissions:
  id-token: write
  contents: write
  packages: read
  pull-requests: read

jobs:

  provision-resources:
    name: "Provision resources"
    runs-on: ubuntu-latest
    # TODO make the determination of the environment dynamic based on branch vs tag
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: aalloul/genesis-action/authenticate-with-gcp@v0.11.0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          gcp_project: ${{ secrets.GCP_SEED_PROJECT }}

      - uses: aalloul/genesis-action/genesis-infra-api@v0.11.0
        with:
          action: provision-resources
          config_yml_file: ${{ matrix.config_file }}
          genesis_version: v0.9.0
          debug: true
          run_terraform_apply: true
          ghcr_token: ${{ secrets.GENESIS_API_ACCESS }}
          repo_admin_token: ${{ secrets.VARS_ACCESS_TOKEN }}
          github_repo_name: ""
          username: 'aalloul'
          folder_id: ${{ vars.FOLDER_ID }}
          cloud_provider: ${{ vars.CLOUD_PROVIDER }}
          gcp_region: ${{ vars.GCP_REGION }}
          gcp_zone: ${{ vars.GCP_ZONE }}
          organization_short_name: ${{ vars.ORGANIZATION_SHORT_NAME }}
          seed_project_id: ${{ vars.SEED_PROJECT_ID }}
          seed_service_account: ${{ vars.SEED_SERVICE_ACCOUNT }}
          billing_account: ${{ secrets.BILLING_ACCOUNT }}
          gcp_seed_project: ${{ secrets.GCP_SEED_PROJECT }}
          gcp_service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          gcp_workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          github_repository_owner: ${{ github.repository_owner }}
          vpcsc_perimeter_name: ${{ vars.VPCSC_PERIMETER_NAME }}
          environment: ${{ vars.ENVIRONMENT }}
          terraform_bucket: ${{ vars.TERRAFORM_BUCKET }}
          organization_name: ${{ vars.ORGANIZATION_NAME }}
          organization_id: ${{ vars.ORGANIZATION_ID }}
